import {
  FoodIcon,
  BarIcon,
  LandmarkIcon,
  ShopIcon,
  BikeIcon,
  AccommodationIcon,
  CafeIcon,
  EntertainmentIcon,
  NaturalIcon,
  ParkingIcon,
  RentalIcon,
  RestaurantIcon,
} from '../assets/icons/categories';

// export const categories = [
//   {
//     id: 0,
//     name: "Food",
//     icon: FoodIcon,
//     color: "#F9B50F",
//     isShown: true,
//   },
//   {
//     id: 1,
//     name: "Bar",
//     icon: BarIcon,
//     color: "#7974ed",
//     isShown: true,
//   },
//   {
//     id: 2,
//     name: "Landmark",
//     icon: LandmarkIcon,
//     color: "#83D15E",
//     isShown: true,
//   },
//   {
//     id: 3,
//     name: "Bike",
//     icon: BikeIcon,
//     color: "#F48F32",
//     isShown: true,
//     size: '3xl',
//   },
//   {
//     id: 4,
//     name: "Shopping",
//     icon: ShopIcon,
//     color: "#EA887B",
//     isShown: true,
//   },
// ];
export const categories = [
  {
    id: 0,
    name: "Restaurant",
    icon: RestaurantIcon,
    color: "#FF8C00",
    searchParams: ["catering.restaurant"],
    isShown: true,
  },
  {
    id: 2,
    name: "Cafe",
    color: "#A52A2A",
    icon: CafeIcon,
    searchParams: ["catering.cafe"],
    isShown: true,
  },
  {
    id: 1,
    name: "Attraction",
    icon: LandmarkIcon,
    color: "#50C878",
    searchParams: [
      "tourism.attraction",
      "tourism.sights",
    ],
    isShown: true,
  },
  {
    id: 3,
    name: "Entertainment",
    color: "#4169E1",
    icon: EntertainmentIcon,
    searchParams: ["entertainment"],
    isShown: true,
  },
  {
    id: 4,
    name: "Shopping",
    color: "#FFD700",
    icon: ShopIcon,
    searchParams: ["commercial"],
    isShown: true,
  },
  {
    id: 5,
    name: "Accommodation",
    icon: AccommodationIcon,
    searchParams: ["accommodation"],
    color: "#6A5ACD",
    isShown: true,
  },
  {
    id: 6,
    name: "Bar",
    icon: BarIcon,
    searchParams: [
      "catering.bar",
      "catering.pub",
      "catering.taproom",
      "catering.biergarten",
    ],
    color: "#800080",
    isShown: true,
  },
  {
    id: 7,
    name: "Natural",
    color: "#228B22",
    searchParams: [
      "natural",
    ],
    icon: NaturalIcon,
    isShown: true,
  },
  {
    id: 8,
    name: "Rental",
    color: "#6E98A0",
    icon: RentalIcon,
    searchParams: [
      "rental",
    ],
    isShown: true,
  },
  {
    id: 9,
    name: "Food",
    color: "#F9B50F",
    icon: FoodIcon,
    isShown: true,
    searchParams: [
      "catering.fast_food",
      "catering.food_court",
      "catering.ice_cream",
      "catering.restaurant",
    ],
  },
  {
    id: 10,
    name: "Parking",
    color: "#6699CC",
    icon: ParkingIcon,
    isShown: true,
    searchParams: [
      "parking",
    ],
  },
];
